"""add_mvp_and_match_photo

Revision ID: 63643ef55af6
Revises: ab8e07467d39
Create Date: 2026-07-21 02:52:12.614047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63643ef55af6'
down_revision = 'ab8e07467d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_match_mvp_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_match_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('voted_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_match_id'], ['group_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_match_id', 'voter_id', name='unique_match_mvp_vote')
    )
    with op.batch_alter_table('group_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_photo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('match_photo_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_matches', schema=None) as batch_op:
        batch_op.drop_column('match_photo_id')
        batch_op.drop_column('match_photo')

    op.drop_table('group_match_mvp_votes')
    # ### end Alembic commands ###
