"""add prize_pool to groups

Revision ID: 8101896f2af4
Revises: 13568af79ce5
Create Date: 2026-04-14 23:25:33.171428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8101896f2af4'
down_revision = '13568af79ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_pool', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('prize_pool')

    # ### end Alembic commands ###
