"""add football fields table

Revision ID: ab8e07467d39
Revises: 5ab46f50e816
Create Date: 2026-07-21 01:41:41.206468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8e07467d39'
down_revision = '5ab46f50e816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('football_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('field_types', sa.String(length=120), nullable=False),
    sa.Column('surface', sa.String(length=60), nullable=False),
    sa.Column('features', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('football_fields')
    # ### end Alembic commands ###
