"""add index to group_messages

Revision ID: b7d0d2905ba6
Revises: ced25389d937
Create Date: 2026-07-29 20:34:56.279385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d0d2905ba6'
down_revision = 'ced25389d937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index('idx_group_messages_group_id', ['group_id', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_group_messages_group_id')

    # ### end Alembic commands ###
